version: "3.5"
services:
  mysql-server:
    image: mysql:5.7
    command: --character-set-server=utf8  --interactive_timeout=120 --wait_timeout=120 --log_warnings=1  --collation-server=utf8_bin --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --lower_case_table_names=1
    restart: always 
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:centos-5.0-latest
    ulimits:
       nproc: 65535
       nofile:
        soft: 20000
        hard: 40000
    cap_add: 
     - ALL
    restart: always
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - ZBX_CACHESIZE=4096M
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    ports:
      - 10051:10051
    sysctls:
     - net.ipv4.ip_local_port_range=1024 65000
     - net.ipv4.conf.all.accept_redirects=0
     - net.ipv4.conf.all.secure_redirects=0
     - net.ipv4.conf.all.send_redirects=0
    links:
      - mysql-server:mysql-server
    depends_on:
      - mysql-server
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix/tmp:/juhe/tmp
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:centos-5.0-latest
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - PHP_TZ=Asia/Shanghai
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    restart: always
    ports:
      - 10002:8080
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:centos-5.0-latest
    privileged: true
    user: root
    restart: always
    cap_add:
    - ALL
    volumes:
     - ../zabbix-agent/script:/etc/zabbix/script
     - ../zabbix-agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
     - /:/rootfs
     - /var/run:/var/run
     - /proc:/proc
     - /etc/timezone:/etc/timezone
    environment:
      ZBX_METADATA: "zabbix server"
      ZBX_HOSTNAME: "Zabbix-server"
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - '10050:10050'
    links:
      - zabbix-server:zabbix-server
    depends_on:
      - zabbix-server
